// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grdhuxslaezevsfatfvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZGh1eHNsYWV6ZXZzZmF0ZnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDU4NDcsImV4cCI6MjA3MjIyMTg0N30.6YPhnZMHhlGqpeJW6ljRkgzIqtqPUcZQ6mLc1KaZ8Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});